package pe.edu.unmsm.urcs.modelo;
// Generated 11/07/2015 09:19:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private String descripcion;
     private Set<Operario> operarios = new HashSet<Operario>(0);
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Area() {
    }

    public Area(String descripcion, Set<Operario> operarios, Set<Servicio> servicios) {
       this.descripcion = descripcion;
       this.operarios = operarios;
       this.servicios = servicios;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Operario> getOperarios() {
        return this.operarios;
    }
    
    public void setOperarios(Set<Operario> operarios) {
        this.operarios = operarios;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


