package pe.edu.unmsm.urcs.modelo;
// Generated 05/07/2015 12:56:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private Integer idArea;
     private String descripcion;
     private Set operarios = new HashSet(0);
     private Set servicios = new HashSet(0);

    public Area() {
    }

    public Area(String descripcion, Set operarios, Set servicios) {
       this.descripcion = descripcion;
       this.operarios = operarios;
       this.servicios = servicios;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getOperarios() {
        return this.operarios;
    }
    
    public void setOperarios(Set operarios) {
        this.operarios = operarios;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


