package pe.edu.unmsm.urcs.modelo;
// Generated 29/06/2015 02:00:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FacultadDependencia generated by hbm2java
 */
public class FacultadDependencia  implements java.io.Serializable {


     private Integer idFacultadDependencia;
     private String descripcion;
     private Set<Oficina> oficinas = new HashSet<Oficina>(0);

    public FacultadDependencia() {
    }

    public FacultadDependencia(String descripcion, Set<Oficina> oficinas) {
       this.descripcion = descripcion;
       this.oficinas = oficinas;
    }
   
    public Integer getIdFacultadDependencia() {
        return this.idFacultadDependencia;
    }
    
    public void setIdFacultadDependencia(Integer idFacultadDependencia) {
        this.idFacultadDependencia = idFacultadDependencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Oficina> getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(Set<Oficina> oficinas) {
        this.oficinas = oficinas;
    }




}


