package pe.edu.unmsm.urcs.modelo;
// Generated 05/07/2015 12:56:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FacultadDependencia generated by hbm2java
 */
public class FacultadDependencia  implements java.io.Serializable {


     private Integer idFacultadDependencia;
     private String descripcion;
     private Set oficinas = new HashSet(0);

    public FacultadDependencia() {
    }

    public FacultadDependencia(String descripcion, Set oficinas) {
       this.descripcion = descripcion;
       this.oficinas = oficinas;
    }
   
    public Integer getIdFacultadDependencia() {
        return this.idFacultadDependencia;
    }
    
    public void setIdFacultadDependencia(Integer idFacultadDependencia) {
        this.idFacultadDependencia = idFacultadDependencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(Set oficinas) {
        this.oficinas = oficinas;
    }




}


