package pe.edu.unmsm.urcs.modelo;
// Generated 29/06/2015 02:00:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Informe generated by hbm2java
 */
public class Informe  implements java.io.Serializable {


     private Integer idInforme;
     private String descripcion;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Informe() {
    }

    public Informe(String descripcion, Set<Solicitud> solicituds) {
       this.descripcion = descripcion;
       this.solicituds = solicituds;
    }
   
    public Integer getIdInforme() {
        return this.idInforme;
    }
    
    public void setIdInforme(Integer idInforme) {
        this.idInforme = idInforme;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


