package pe.edu.unmsm.urcs.modelo;
// Generated 05/07/2015 12:56:44 AM by Hibernate Tools 4.3.1



/**
 * Oficina generated by hbm2java
 */
public class Oficina  implements java.io.Serializable {


     private OficinaId id;
     private FacultadDependencia facultadDependencia;
     private String descripcion;

    public Oficina() {
    }

	
    public Oficina(OficinaId id, FacultadDependencia facultadDependencia) {
        this.id = id;
        this.facultadDependencia = facultadDependencia;
    }
    public Oficina(OficinaId id, FacultadDependencia facultadDependencia, String descripcion) {
       this.id = id;
       this.facultadDependencia = facultadDependencia;
       this.descripcion = descripcion;
    }
   
    public OficinaId getId() {
        return this.id;
    }
    
    public void setId(OficinaId id) {
        this.id = id;
    }
    public FacultadDependencia getFacultadDependencia() {
        return this.facultadDependencia;
    }
    
    public void setFacultadDependencia(FacultadDependencia facultadDependencia) {
        this.facultadDependencia = facultadDependencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


