package pe.edu.unmsm.urcs.modelo;
// Generated 11/07/2015 09:19:57 PM by Hibernate Tools 4.3.1



/**
 * Oficina generated by hbm2java
 */
public class Oficina  implements java.io.Serializable {


     private Integer idOficina;
     private FacultadDependencia facultadDependencia;
     private String descripcion;

    public Oficina() {
    }

	
    public Oficina(FacultadDependencia facultadDependencia) {
        this.facultadDependencia = facultadDependencia;
    }
    public Oficina(FacultadDependencia facultadDependencia, String descripcion) {
       this.facultadDependencia = facultadDependencia;
       this.descripcion = descripcion;
    }
   
    public Integer getIdOficina() {
        return this.idOficina;
    }
    
    public void setIdOficina(Integer idOficina) {
        this.idOficina = idOficina;
    }
    public FacultadDependencia getFacultadDependencia() {
        return this.facultadDependencia;
    }
    
    public void setFacultadDependencia(FacultadDependencia facultadDependencia) {
        this.facultadDependencia = facultadDependencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


