package pe.edu.unmsm.urcs.modelo;
// Generated 05/07/2015 12:56:44 AM by Hibernate Tools 4.3.1



/**
 * Opcion generated by hbm2java
 */
public class Opcion  implements java.io.Serializable {


     private OpcionId id;
     private Perfil perfil;
     private String descripcion;

    public Opcion() {
    }

	
    public Opcion(OpcionId id, Perfil perfil) {
        this.id = id;
        this.perfil = perfil;
    }
    public Opcion(OpcionId id, Perfil perfil, String descripcion) {
       this.id = id;
       this.perfil = perfil;
       this.descripcion = descripcion;
    }
   
    public OpcionId getId() {
        return this.id;
    }
    
    public void setId(OpcionId id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


