package pe.edu.unmsm.urcs.modelo;
// Generated 05/07/2015 12:56:44 AM by Hibernate Tools 4.3.1



/**
 * OpcionId generated by hbm2java
 */
public class OpcionId  implements java.io.Serializable {


     private int idOpcion;
     private int perfilIdPerfil;

    public OpcionId() {
    }

    public OpcionId(int idOpcion, int perfilIdPerfil) {
       this.idOpcion = idOpcion;
       this.perfilIdPerfil = perfilIdPerfil;
    }
   
    public int getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(int idOpcion) {
        this.idOpcion = idOpcion;
    }
    public int getPerfilIdPerfil() {
        return this.perfilIdPerfil;
    }
    
    public void setPerfilIdPerfil(int perfilIdPerfil) {
        this.perfilIdPerfil = perfilIdPerfil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OpcionId) ) return false;
		 OpcionId castOther = ( OpcionId ) other; 
         
		 return (this.getIdOpcion()==castOther.getIdOpcion())
 && (this.getPerfilIdPerfil()==castOther.getPerfilIdPerfil());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOpcion();
         result = 37 * result + this.getPerfilIdPerfil();
         return result;
   }   


}


