package pe.edu.unmsm.urcs.modelo;
// Generated 29/06/2015 02:00:34 PM by Hibernate Tools 4.3.1



/**
 * SolicitudId generated by hbm2java
 */
public class SolicitudId  implements java.io.Serializable {


     private int idSolicitud;
     private int informeIdInforme;
     private int usuarioIdUsuario;
     private int estadoIdEstado;
     private int servicioIdServicio;
     private int operarioIdOperario;

    public SolicitudId() {
    }

    public SolicitudId(int idSolicitud, int informeIdInforme, int usuarioIdUsuario, int estadoIdEstado, int servicioIdServicio, int operarioIdOperario) {
       this.idSolicitud = idSolicitud;
       this.informeIdInforme = informeIdInforme;
       this.usuarioIdUsuario = usuarioIdUsuario;
       this.estadoIdEstado = estadoIdEstado;
       this.servicioIdServicio = servicioIdServicio;
       this.operarioIdOperario = operarioIdOperario;
    }
   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public int getInformeIdInforme() {
        return this.informeIdInforme;
    }
    
    public void setInformeIdInforme(int informeIdInforme) {
        this.informeIdInforme = informeIdInforme;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public int getEstadoIdEstado() {
        return this.estadoIdEstado;
    }
    
    public void setEstadoIdEstado(int estadoIdEstado) {
        this.estadoIdEstado = estadoIdEstado;
    }
    public int getServicioIdServicio() {
        return this.servicioIdServicio;
    }
    
    public void setServicioIdServicio(int servicioIdServicio) {
        this.servicioIdServicio = servicioIdServicio;
    }
    public int getOperarioIdOperario() {
        return this.operarioIdOperario;
    }
    
    public void setOperarioIdOperario(int operarioIdOperario) {
        this.operarioIdOperario = operarioIdOperario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SolicitudId) ) return false;
		 SolicitudId castOther = ( SolicitudId ) other; 
         
		 return (this.getIdSolicitud()==castOther.getIdSolicitud())
 && (this.getInformeIdInforme()==castOther.getInformeIdInforme())
 && (this.getUsuarioIdUsuario()==castOther.getUsuarioIdUsuario())
 && (this.getEstadoIdEstado()==castOther.getEstadoIdEstado())
 && (this.getServicioIdServicio()==castOther.getServicioIdServicio())
 && (this.getOperarioIdOperario()==castOther.getOperarioIdOperario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSolicitud();
         result = 37 * result + this.getInformeIdInforme();
         result = 37 * result + this.getUsuarioIdUsuario();
         result = 37 * result + this.getEstadoIdEstado();
         result = 37 * result + this.getServicioIdServicio();
         result = 37 * result + this.getOperarioIdOperario();
         return result;
   }   


}


