package pe.edu.unmsm.urcs.modelo;
// Generated 11/07/2015 09:19:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int idSolicitud;
     private Estado estado;
     private Operario operario;
     private Servicio servicio;
     private Usuario usuario;
     private Date fechaEnviado;
     private Date fechaProceso;
     private Date fechaPendienteReasig;
     private Date fechaFinalizado;
     private String motivoReasignacion;
     private String anexo;
     private String informe;

    public Solicitud() {
    }

	
    public Solicitud(int idSolicitud, Estado estado, Operario operario, Servicio servicio, Usuario usuario, Date fechaEnviado) {
        this.idSolicitud = idSolicitud;
        this.estado = estado;
        this.operario = operario;
        this.servicio = servicio;
        this.usuario = usuario;
        this.fechaEnviado = fechaEnviado;
    }
    public Solicitud(int idSolicitud, Estado estado, Operario operario, Servicio servicio, Usuario usuario, Date fechaEnviado, Date fechaProceso, Date fechaPendienteReasig, Date fechaFinalizado, String motivoReasignacion, String anexo, String informe) {
       this.idSolicitud = idSolicitud;
       this.estado = estado;
       this.operario = operario;
       this.servicio = servicio;
       this.usuario = usuario;
       this.fechaEnviado = fechaEnviado;
       this.fechaProceso = fechaProceso;
       this.fechaPendienteReasig = fechaPendienteReasig;
       this.fechaFinalizado = fechaFinalizado;
       this.motivoReasignacion = motivoReasignacion;
       this.anexo = anexo;
       this.informe = informe;
    }
   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Operario getOperario() {
        return this.operario;
    }
    
    public void setOperario(Operario operario) {
        this.operario = operario;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaEnviado() {
        return this.fechaEnviado;
    }
    
    public void setFechaEnviado(Date fechaEnviado) {
        this.fechaEnviado = fechaEnviado;
    }
    public Date getFechaProceso() {
        return this.fechaProceso;
    }
    
    public void setFechaProceso(Date fechaProceso) {
        this.fechaProceso = fechaProceso;
    }
    public Date getFechaPendienteReasig() {
        return this.fechaPendienteReasig;
    }
    
    public void setFechaPendienteReasig(Date fechaPendienteReasig) {
        this.fechaPendienteReasig = fechaPendienteReasig;
    }
    public Date getFechaFinalizado() {
        return this.fechaFinalizado;
    }
    
    public void setFechaFinalizado(Date fechaFinalizado) {
        this.fechaFinalizado = fechaFinalizado;
    }
    public String getMotivoReasignacion() {
        return this.motivoReasignacion;
    }
    
    public void setMotivoReasignacion(String motivoReasignacion) {
        this.motivoReasignacion = motivoReasignacion;
    }
    public String getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(String anexo) {
        this.anexo = anexo;
    }
    public String getInforme() {
        return this.informe;
    }
    
    public void setInforme(String informe) {
        this.informe = informe;
    }




}


